### ISSUE TITLE
Allow for more/custom list styles

### ISSUE THREAD

**Issue by lukasoppermann** [joeoak/al-list#1]
Hey, I love it! 

It would be awesome if you could allow users to do customize the list-styles more.

1. Allow for custom text so I can just put in any character like — or # or 👍

2. Option to turn bullet into component (this would allow users to later on change just one component and edit the whole list)

2.1. Allow to use a component as the bullet option (maybe this could be instead of 2)

**Comment by joeoak** [comment]
Thanks for the feedback, Lukas!

1. Custom bullets would be great 👍. Thinking of adding ordered list options as well (numbered, maybe lettered).
2. Right on. I could see this being particularly useful in instances where someone would want vectors or shapes as bullets.
